#!/usr/bin/env python3
"""Derive complete guest hooks with narrowly scoped operand substitutions.

Default mode verifies checked-in lifts. --write updates only src/*.inc; it never
edits/recompiles the generated game. Hash changes require reviewing the retail
function again before updating the expected source identity.
"""

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FUNCTIONS = (
    ("sub_821D6260", "5", "5f1ed89078e9675539f66cb9222e722a670ae6e25e54cd9721ac1b333e88b43d", "r9"),
    ("sub_821D8CD8", "5", "e9c4683f6ac6162b3cd370ed2749604ad2a1de9ef35c6b1d37edb23de4882bdb", "r11"),
    ("sub_822551E0", "9", "a3263f41a0fcb3092261051fbd8a78f3e7c7980da8a7c0a5cd76494305120e6b", None),
)
HEADER = """// Derived by tools/derive_draw_distance_hooks.py --write.
// Complete retail PPC logic; only the documented operand below is replaced.
// Run that script without --write to verify against the generated originals.
// Do not edit this file by hand.

"""


def derive(name: str, unit: str, expected: str, register: str | None) -> str:
    source = (ROOT / "generated" / f"gta4_recomp.{unit}.cpp").read_text()
    signature = f"DEFINE_REX_FUNC({name}) {{"
    start = source.index(signature)
    end = source.find("\nDEFINE_REX_FUNC(", start + 1)
    body = source[start:end] if end != -1 else source[start:]
    actual = hashlib.sha256(body.encode()).hexdigest()
    if actual != expected:
        raise SystemExit(f"{name}: generated source changed ({actual}); review before deriving")
    if register:
        guard = f"""extern "C" void {name}(PPCContext& ctx, uint8_t* base) {{
  if (!IsNativeMode()) {{
    __imp__{name}(ctx, base);
    return;
  }}
  const float native_remap_limit = gta4::draw_distance::ResolveRemapLimit(
      LoadF32(base, kDistanceScaleInputGlobal));"""
        old = f"temp.u32 = REX_LOAD_U32(ctx.{register}.u32 + 9492);"
        new = "temp.u32 = std::bit_cast<uint32_t>(native_remap_limit);"
    else:
        # The aspect hook owns the retail entry point and scopes this complete
        # slider implementation, so both extensions share one strong symbol.
        guard = f"""void gta4::frontend_menu::DrawSliders(PPCContext& ctx, uint8_t* base) {{
  if (!IsDisplayScreen(base) || !IsOwnedAdvancedPage(base)) {{
    __imp__{name}(ctx, base);
    return;
  }}"""
        old = "ctx.r11.u64 = REX_LOAD_U32(ctx.r11.u32 + ctx.r24.u32);"
        # r25 is the row index at this one preference load in the retail draw.
        # Every other slider (including stock brightness) keeps its own value.
        new = "ctx.r11.u64 = ReadFrontendSliderPosition(base, ctx.r25.s32, ctx.r11.u32 + ctx.r24.u32);"
    if body.count(old) != 1:
        raise SystemExit(f"{name}: expected exactly one operand site")
    body = body.replace(signature, guard, 1).replace(old, new, 1)
    if register is None:
        # The retail slider page never scrolls. The owned Advanced page does;
        # share its row viewport so the bar follows its label and is clipped.
        replacements = {
            "ctx.f28.f64 = double(float(ctx.f0.f64 + ctx.f13.f64));":
                "ctx.f28.f64 = FrontendSliderStartY(ctx.f0.f64, ctx.f13.f64);",
            "ctx.r10.u64 = REX_LOAD_U8(ctx.r10.u32 + 21);":
                "ctx.r10.u64 = ReadFrontendSliderDisplayType(base, ctx.r25.s32, ctx.r10.u32 + 21);",
        }
        for old, new in replacements.items():
            if body.count(old) != 1:
                raise SystemExit(f"{name}: expected exactly one slider viewport operand")
            body = body.replace(old, new, 1)
    return body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    bodies = [derive(*spec) for spec in FUNCTIONS]
    outputs = {
        "gta4_draw_distance_guest.inc": HEADER + "\n".join(bodies[:2]),
        "gta4_frontend_slider_guest.inc": HEADER + bodies[2],
    }
    for name, text in outputs.items():
        path = ROOT / "src" / name
        if args.write:
            path.write_text(text)
        elif not path.exists() or path.read_text() != text:
            raise SystemExit(f"{path}: differs from the reviewed derivation")
        print(f"{name}: verified complete retail logic and local operand substitutions")


if __name__ == "__main__":
    main()
